language: java
install: true

jdk: oraclejdk8

jobs:
  include:
    - stage: build
      script: ./gradlew build -s
    - stage: release
      script: skip
      deploy:
        provider: script
        script: ./gradlew bintrayUpload -s
        on:
          tags: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
